ServerUrl: "https://mattermost.server.com"
Channel: "bot channel name"
Email: "bot email"
Password: "bot password"
Team: "bot team"
FbAccessToken: "TOKEN"
FbPageId: 123
PostPhraseToSearch: "lunch!"
PostCheckIntervalMin: 30
PostCheckIntervalBeforeMin: 80
PostCheckIntervalAfterMax: 180

